export const categoryColors = [
    { name: "Crimson Red",    hex: "#E63946" },
    { name: "Coral Orange",   hex: "#F4845F" },
    { name: "Amber",          hex: "#F4A261" },
    { name: "Sunflower",      hex: "#E9C46A" },
    { name: "Lime Green",     hex: "#90BE6D" },
    { name: "Emerald",        hex: "#43AA8B" },
    { name: "Teal",           hex: "#4D908E" },
    { name: "Sky Blue",       hex: "#4CC9F0" },
    { name: "Royal Blue",     hex: "#4361EE" },
    { name: "Indigo",         hex: "#3A0CA3" },
    { name: "Violet",         hex: "#7209B7" },
    { name: "Magenta",        hex: "#F72585" },
    { name: "Hot Pink",       hex: "#FF006E" },
    { name: "Peach",          hex: "#FFBA92" },
    { name: "Mint",           hex: "#80FFDB" },
    { name: "Lavender",       hex: "#C77DFF" },
    { name: "Periwinkle",     hex: "#8187DC" },
    { name: "Steel Blue",     hex: "#457B9D" },
    { name: "Ocean",          hex: "#1D7A8A" },
    { name: "Forest Green",   hex: "#2D6A4F" },
    { name: "Olive",          hex: "#A7C957" },
    { name: "Mustard",        hex: "#E9B44C" },
    { name: "Burnt Orange",   hex: "#CC5803" },
    { name: "Rose",           hex: "#FF5D8F" },
    { name: "Mauve",          hex: "#C9B1BD" },
    { name: "Dusty Purple",   hex: "#9B72AA" },
    { name: "Slate",          hex: "#6C757D" },
    { name: "Copper",         hex: "#CB6D51" },
    { name: "Turquoise",      hex: "#06D6A0" },
    { name: "Neon Yellow",    hex: "#CCFF00" },
  ];